DjangoProjectShop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import  Home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name='home'),
    path('users/',include('Users.urls',namespace='Users')),
    path('product/',include('Product.urls',namespace='Product')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from .views import LoginView,ProfileView,RegisterView,LogoutView,UserChangePassword
app_name = 'Users'
urlpatterns = [
    path('login',LoginView,name='login'),
    path('profile',ProfileView.as_view(),name='profile'),
    path('register',RegisterView,name="register"),
    path('logout',LogoutView,name="logout"),
    path("passwordchange",UserChangePassword.as_view(),name='changepassword')

]

Users/models.py
from datetime import timezone

import jdatetime
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager
from django.utils import timezone

class CustomeUser(AbstractUser):
    username = None
    Image=models.ImageField(upload_to='Users/images/',blank=True,null=True)
    mobile=models.CharField(("موبایل"),unique=True,max_length=11,)
    USERNAME_FIELD = "mobile"
    REQUIRED_FIELDS = []
    objects = CustomUserManager()
    class Meta:
        verbose_name = "کاربران"
        verbose_name_plural="کاربران"

    def __str__(self):
        return self.mobile

    def get_shamsi_datetime(self):
        return jdatetime.datetime.fromgregorian(date=self.date_time.date(), time=self.date_time.time()).strftime(
            '%Y/%m/%d %H:%M:%S')

    # def get_jalali_date(self):
    #     return jdatetime.date.fromgregorian(date_joined=self.date_joined).strftime('%Y/%m/%d')

Users/forms.py
from  django import  forms
from .models import CustomeUser
class LoginForm(forms.Form):
    Mobile=forms.CharField(max_length=11,label="موبایل",widget=forms.TextInput(attrs={
        'class':'e-field-inner',
        'placeholder':'لطفا موبایل خود را وارد نمایید',
        'id':"LoginMobile"
    }))
    Password=forms.CharField(max_length=11,label="رمز عبور",widget=forms.PasswordInput(attrs={
        'class':'e-field-inner',
        'placeholder': 'لطفا رمز عبور خود را وارد نمایید',
        'id':'LoginPassword'
    }))
class RegisterForm(forms.ModelForm):
    Password = forms.CharField(max_length=30, required=True, label=" رمز عبور",
                                 widget=forms.PasswordInput(attrs={
                                     'class': 'e-field-inner',
                                     'placeholder': 'لطفا رمز عبور خود را وارد نمایید',
                                     'id': 'RegisterPassword'
                                 }))
    RePassword=forms.CharField(max_length=30,required=True,label="تکرار رمز عبور",widget=forms.PasswordInput(attrs={
        'class': 'e-field-inner',
        'placeholder': 'لطفا تکرار رمز عبور خود را وارد نمایید',
        'id':'RegisterRePassword'
    }))
    class Meta:


        model=CustomeUser
        fields=['mobile','Password',"RePassword"]
        error_messages = {
           'mobile':{
               'required':'این فیلد اجباری میباشد',
               'max_length':'شماره موبایل نمیتواند بیشتر از 11 کاراکتر باشد'
           },



        }
        required={
        'mobile':True,

        }
        labels = {
            'mobile':"شماره تلفن",
            'password':'رمز عبور'


        }
        widgets={
            "mobile":forms.TextInput(attrs={
                'class': 'e-field-inner',
                'placeholder': 'لطفا موبایل خود را وارد نمایید',
                'id':'RegisterMobile'
            }),
            'password':forms.PasswordInput(attrs={
                'class': 'e-field-inner',
                'placeholder': 'لطفا رمز  عبور خود را وارد نمایید',
            }),

        }


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = CustomeUser
        fields = ('first_name','last_name','email','Image')
        labels={
            "first_name":"نام",
            "last_name":"نام خانوادگی",
            "email":"ایمیل",
            "Image":"تصویر کاربری"
        }
        widgets={
            "first_name":forms.TextInput(attrs={
                'class':'e-field-inner',
                 'placeholder':"نام خود را وارد نمایید"
            }),
            "last_name": forms.TextInput(attrs={
                'class': 'e-field-inner',
                'placeholder': "نام خانوادگی خود را وارد نمایید"
            }),
            "email": forms.EmailInput(attrs={
                'class': 'e-field-inner',
                'placeholder': "ایمیل خود را وارد نمایید"
            }),
        "Image": forms.FileInput(attrs={
            'id':"user_profile"
        })


        }

class PasswrodChangeForm(forms.Form):
    CurrentPassword = forms.CharField(max_length=30, required=True, label=" رمز عبور",
widget=forms.PasswordInput(attrs={
'class': 'e-field-inner',
 'placeholder': 'لطفا رمز عبور خود را وارد نمایید',
 'id': 'CurrentPassword_id'
 }))

    Password = forms.CharField(max_length=30, required=True, label=" رمز عبور",
widget=forms.PasswordInput(attrs={
'class': 'e-field-inner',
'placeholder': 'لطفا رمز عبور خود را وارد نمایید',
 'id': 'ChangePassword_id'
}))
    RePassword = forms.CharField(max_length=30, required=True, label="تکرار رمز عبور",widget=forms.PasswordInput(attrs={
'class': 'e-field-inner','placeholder': 'لطفا تکرار رمز عبور خود را وارد نمایید','id': 'ChanegRePassword_id'
                                 }))

Users/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from .forms import  PasswrodChangeForm
from django.views.generic import  DeleteView
from  Users.models import  CustomeUser
from .forms import LoginForm,EditProfileForm,RegisterForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.mixins import LoginRequiredMixin



def LoginView(request):
    form=LoginForm(request.POST)
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            Mobile=form.cleaned_data['Mobile']
            Password=form.cleaned_data['Password']
            user=authenticate(mobile=Mobile,password=Password)
            if user is not None:
                login(request,user)

                return  JsonResponse({"result":"success"})

            return  JsonResponse({'result':'error'})
    return  render(request, 'Home.html',{'form':form})


def RegisterView(request):
    Register=RegisterForm()
    if request.method == 'POST':
        Register=RegisterForm(request.POST)
        if  Register.is_valid():
            password =  Register.cleaned_data['Password']
            user = CustomeUser.objects.filter(mobile= Register.cleaned_data['mobile']).first()
            if user :
                return  JsonResponse({'reponse':'found'})
            else:
                user1 = Register.save(commit=False)
                user1.set_password(password)
                user1.save()
            return redirect('/')

    return render(request,"Home.html",{' Register': Register})



def LogoutView(request):
    logout(request)
    return redirect('/')


class ProfileView(LoginRequiredMixin,View):
    login_url = 'Users:login'
    def get(self, request):
        profile = get_object_or_404(CustomeUser, mobile=request.user.mobile)
        form=EditProfileForm(instance=profile)
        return render(request,'Profile.html',{'form':form,'profile':profile})
    def post(self, request):
        profile = get_object_or_404(CustomeUser, mobile=request.user.mobile)
        form=EditProfileForm(request.POST,request.FILES,instance=profile)
        if form.is_valid():
             form.save()
             return redirect("Users:profile")




class UserChangePassword(LoginRequiredMixin,View):
    def get(self,request):
        form = PasswrodChangeForm()
        return  render(request,"UserChangePassword.html",{'form':form})
    def post(self,request):
        form = PasswrodChangeForm()
        if form.is_valid():
             CurrentPassword=form.cleaned_data[' CurrentPassword']
             pass1 = form.cleaned_data['Password']
             pass2 = form.cleaned_data['RePassword']
             user=self.request.user
             User=CustomeUser.objects.filter(mobile=user.mobile).first()
             if User and User.check_password(CurrentPassword) :
                User.set_password(pass1)
                User.save()
                logout(request)
                return  JsonResponse({"status":"success"})
             elif(pass1!=pass2):
                 return  JsonResponse({"status":"NotMatch"})
             else:
                     return JsonResponse({"status":"error"})

        return  render(request,'UserChangePassword.html')

Users/templates/Profile.html
{% extends 'Shared/Base.html' %}
{% load static %}
{% block content %}

<!-- Product Category start -->
<div class="e-profile-wrap e-profile-cloth">
    <div class="container">
    <form method="post" action="{% url 'Users:profile' %}" enctype="multipart/form-data">
        <div class="row">
            <div class="col-12">
                <div class="e-profile-inner">
                    <div class="e-profile-img">
                        <div class="e-userpro-img">
                               {% if profile.Image  %}
                                <img src="{{ profile.Image.url }}" alt="image">
                                {% endif %}
                                {{ form.Image }}

                            <label for="user_profile">
                                <span>
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="20px" height="20px" viewBox="0 0 485.219 485.22" style="enable-background:new 0 0 485.219 485.22;" xml:space="preserve">
                                    <g>
                                        <path fill="#ffffff" d="M467.476,146.438l-21.445,21.455L317.35,39.23l21.445-21.457c23.689-23.692,62.104-23.692,85.795,0l42.886,42.897
                                            C491.133,84.349,491.133,122.748,467.476,146.438z M167.233,403.748c-5.922,5.922-5.922,15.513,0,21.436
                                            c5.925,5.955,15.521,5.955,21.443,0L424.59,189.335l-21.469-21.457L167.233,403.748z M60,296.54c-5.925,5.927-5.925,15.514,0,21.44
                                            c5.922,5.923,15.518,5.923,21.443,0L317.35,82.113L295.914,60.67L60,296.54z M338.767,103.54L102.881,339.421
                                            c-11.845,11.822-11.815,31.041,0,42.886c11.85,11.846,31.038,11.901,42.914-0.032l235.886-235.837L338.767,103.54z
                                                M145.734,446.572c-7.253-7.262-10.749-16.465-12.05-25.948c-3.083,0.476-6.188,0.919-9.36,0.919
                                            c-16.202,0-31.419-6.333-42.881-17.795c-11.462-11.491-17.77-26.687-17.77-42.887c0-2.954,0.443-5.833,0.859-8.703
                                            c-9.803-1.335-18.864-5.629-25.972-12.737c-0.682-0.677-0.917-1.596-1.538-2.338L0,485.216l147.748-36.986
                                            C147.097,447.637,146.36,447.193,145.734,446.572z"></path>
                                    </g>
                                    </svg>
                                </span>
                            </label>

                        </div>
                    </div>

                    <div class="e-profile-box">

                            {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 ">
                                <div class="e-form-field mb-26">
                                    {{ form.first_name.label_tag }}
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-md-6 ">
                                <div class="e-form-field mb-26">
                                    {{ form.last_name.label_tag }}
                                  {{ form.last_name }}
                                </div>
                            </div>
                            <div class="col-md-6 ">
                                <div class="e-form-field mb-26">
                                   {{ form.email.label_tag }}
                                  {{ form.email }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="">
                                    <button type="submit" class="e-btn">ذخیره</button>
                                </div>
                            </div>

                        </div>
                        </form>
                            <div class="col-md-12">
                                    <div class="">
                                       <a href="{% url 'Users:changepassword' %}">تغییر رمز عبور</a>
                                    </div>
                            </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

Users/templates/UserChangePassword.html
{% extends 'Shared/Base.html' %}
{% block content %}
   <div class="e-forgotpassword-wrap e-forgotpassword-cloth">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="e-fp-box">
                    <form action="{% url "Users:changepassword" %}" method="post" id="Passchange_form" novalidate>
                        <div class="row">
                            {% csrf_token %}
                            <div class="col-md-12">
                            </div>
                             <div class="col-md-12">
                               <div class="e-form-field mb-20">
                                    <label>رمز عبور فعلی</label>
                                   {{ form.CurrentPassword }}

                                   <div class="password_error" id="currentpassword"></div>
                                </div>
                            </div>
                            <div class="col-md-12">
                               <div class="e-form-field mb-20">
                                    <label>رمز عبور </label>
                                   {{ form.Password }}
                                   <div class="password_error" id="newpassword"></div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="e-form-field mb-20">
                                    <label>تکرار رمز عبور</label>
                                    {{ form.RePassword }}
                                    <div class="password_error" id="newrepassword"></div>
                                    <div class="password_error" id="matchpassword"></div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="">
                                    <button type="submit" class="e-btn">تغییر رمز عبور</button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}