DjangoProjectShop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import  Home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name='home'),
    path('users/',include('Users.urls',namespace='Users')),
    path('product/',include('Product.urls',namespace='Product')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/urls.py
from django.urls import  path
from .views import ProductDetailView,ProductFaviorate,AddProductFaviorate,DeleteProductFaviorate
app_name='Product'
urlpatterns=[
    path('detail/<int:id>/',ProductDetailView,name='ProductDetail'),
    path('wishlist',ProductFaviorate,name='Productfaviorate'),
    path("addfaviorate/<int:id>/",AddProductFaviorate,name="addfaviorate"),
    path("deletefaviorate/<int:item_id>/",DeleteProductFaviorate,name="deleteproductfaviorate")
]

Users/urls.py
from django.urls import path
from .views import LoginView,ProfileView,RegisterView,LogoutView,UserChangePassword
app_name = 'Users'
urlpatterns = [
    path('login',LoginView,name='login'),
    path('profile',ProfileView.as_view(),name='profile'),
    path('register',RegisterView,name="register"),
    path('logout',LogoutView,name="logout"),
    path("passwordchange",UserChangePassword.as_view(),name='changepassword')

]

Product/models.py
from django.db import models
from Category.models import Category
from DjangoProjectShop import settings


class Color(models.Model):
    name = models.CharField(max_length=20, unique=True)
    color_name=models.CharField(max_length=20,null=True)
    def __str__(self):
        return self.color_name

    class Meta:
        verbose_name = "رنگ"
        verbose_name_plural = "رنگ ها"
class Size(models.Model):
    name = models.CharField(max_length=10, unique=True)

    class Meta:
        verbose_name = "سایز"
        verbose_name_plural = "سایز"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50,verbose_name='نام محصول')
    description = models.TextField(blank=True, null=True,verbose_name='توضیحات')
    base_price = models.PositiveSmallIntegerField(verbose_name='قیمت محصول')
    category = models.ForeignKey(Category, on_delete=models.CASCADE,verbose_name='دسته بندی محصول')
    Image=models.ImageField(upload_to="Products/Images",null=True,blank=True,verbose_name='عکس محصول')
    class Meta:
        verbose_name="محصول"
        verbose_name_plural="محصولات"
    def __str__(self):
        return self.name


class ProductVariation(models.Model):
    product = models.ForeignKey(Product, related_name='variations', on_delete=models.CASCADE,verbose_name='نام محصول')
    color = models.ForeignKey(Color, on_delete=models.CASCADE,verbose_name='رنگ محصول')
    size = models.ForeignKey(Size, on_delete=models.CASCADE,verbose_name='سایز محصول')


    class Meta:
        verbose_name = "ویژگی محصول"
        verbose_name_plural = " ویژگی محصولات"
    def __str__(self):
        return f'{self.product.name} - {self.color.color_name} - {self.size.name}'
class Faviorate(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='favorites')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='favorites',verbose_name="نام محصول")
    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'product'], name='unique_favorite')
        ]
        verbose_name="علاقه مندی"
        verbose_name_plural="علاقه مندی ها"

Product/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect

from .models import Product,ProductVariation,Faviorate
from django.shortcuts import get_object_or_404
from django.db.models import Min
from .models import Product
from django.contrib.auth.decorators import login_required
def ProductDetailView(request,id):
    product = Product.objects.filter(id=id).first()

    uniq_colors=ProductVariation.objects.filter(product=product).prefetch_related('variations').values('color').annotate(min_id=Min('id')).values('min_id')

    unique_sizes = ProductVariation.objects.filter(product=product).values('size').annotate(min_id=Min('id')).values('min_id')
    print(unique_sizes)
    unique_variations = ProductVariation.objects.filter(id__in=unique_sizes)
    unique_variation_color= ProductVariation.objects.filter(id__in=uniq_colors)

    context={
        "unique_size":unique_variations,
         "unique_variation_color": unique_variation_color,
         'product':product,

    }


    return render(request,'Product_Detail.html',context)

@login_required(login_url="/")
def ProductFaviorate(request):
    UserFaviorats=Faviorate.objects.filter(user=request.user)
    print(UserFaviorats)

    print(UserFaviorats)
    context={
        "UserFaviorats":UserFaviorats
    }
    return  render(request,"wishlist.html",context)

@login_required(login_url="/")
def AddProductFaviorate(request,id):
        product=get_object_or_404(Product,id=id)
        user=request.user
        Addfaviorate=Faviorate.objects.filter(product=product,user=user).exists()
        if Addfaviorate :
             return  JsonResponse({'status':'Found'})
        else:
            Faviorate.objects.create(product=product,user=user)
            return  JsonResponse({"status":'Added'})
        return  render(request,'wishlist.html')

def DeleteProductFaviorate(request,item_id):
    if request.method== 'POST':
        item = get_object_or_404(Faviorate, id=item_id, user=request.user)
        item.delete()
    return redirect('Product:Productfaviorate')

Product/templates/Product_Detail.html
{% extends 'Shared/Base.html' %}
{% load humanize %}

{% load static %}
{% block content %}
<section class="e-prodetails-wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-12">
                <div class="pd-gallery-wrap">
                    <div class="pd-thumb-box">
                        <ul class="pd-thumb-list">
                            <li class="active">
                                <img src="{% static 'assets/images/index1/pro-singlethumb01.jpg' %}" alt="product-img" data-source="{% static '' %}assets/images/index1/pro-single01.jpg" class="pro_thumb">
                            </li>
                            <li>
                                <img src="{% static 'assets/images/index1/pro-singlethumb02.jpg' %}" alt="product-img" data-source="{% static 'assets/images/index1/pro-single02.jpg' %}" class="pro_thumb">
                            </li>
                            <li>
                                <img src="{% static 'assets/images/index1/pro-singlethumb03.jpg' %}" alt="product-img" data-source="{% static 'assets/images/index1/pro-single03.jpg' %}" class="pro_thumb">
                            </li>
                        </ul>
                    </div>
                    <div class="pd-img-wrap">
                        <div class="pd-img text-center">
                            <img src="{% static 'assets/images/index1/pro-single01.jpg' %}" alt="product-img">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="prodetails-info">
                    <div class="pd-infotop">
                        <h2 class="pd-title">{{ product.name }}</h2>
                        <div class="pd-special-price">
                            <span class="pd-price-end" id="headline">قیمت ویژه در کمتر از</span>
                            <div id="countdown">
                                <ul class="pd-counter-list">
                                  <li><span id="days"></span> روز : </li>
                                  <li><span id="hours"></span> ساعت : </li>
                                  <li><span id="minutes"></span> دقیقه : </li>
                                  <li><span id="seconds"></span> ثانیه پایان می می رسد</li>
                                </ul>
                            </div>
                        </div>
                        <ul class="pd-price-wrap">
                                 <li><span class="pd-price-ttile"> تومان{{ product.base_price|intcomma }}</span>  </li>
                            <li><span class="pd-price-off">10% تخفیف </span></li>
                        </ul>
                    </div>
                    <div class="pd-info-bottom">
                        <ul class="info-bottom-list">
                            <li>
                                <div class="ib-list-left">
                                    <span>رنگ های موجود</span>
                                </div>
                                <div class="ib-list-right">
                                    <ul class="na-color-skin">
                                        {% for ProductColor in unique_variation_color %}
                                        <li class="color-box" data-color="{{ ProductColor.color.name }}"  style="--color: {{ ProductColor.color.name }}; "></li>
                                            {% endfor %}
                                    </ul>
                                      <input type="hidden" id="selected-color" name="color" value="">
                                </div>
                            </li>
                            <li>
                                <div class="ib-list-left">
                                    <span>سایز های موجود</span>
                                </div>
                                <div class="ib-list-right">
                                    <ul class="pd-info-size d-flex">
                                  {% for item in unique_size %}
                                             <li class="size-box" data-size="{{ item.size }}">{{ item.size }}</li>
                                       {% endfor %}
                                    </ul>
                                <input type="hidden" id="selected-size" name="size" value="">
                                </div>
                            </li>
                            <li>
{#                                <div class="ib-list-left">#}
{#                                    <span>ارائه به </span>#}
{#                                </div>#}
{#                                <div class="ib-list-right">#}
{#                                    <div class="pd-info-pincode">#}
{#                                        <div class="e-nl-box boreder  pd-info-pinbox">#}
{#                                            <input type="text" placeholder="کد رمز خود را وارد کنید...">#}
{#                                            <a href="javascript:void(0);" class="e-btn newsletter-btn">بررسی </a>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
                            </li>
                            <li>
                                <div class="ib-list-left">
                                    <span>تعداد </span>
                                </div>
                                <div class="ib-list-right">
                                    <ul class="pd-qua-wrap">
                                        <li>
                                            <div class="quantity-box">
                                                <input type="text" class="quantity" value="2">
                                                <span class="quantity-minus pa-sub quantity-icon"> - </span>
                                                <span class="quantity-plus  pa-add quantity-icon"> + </span>
                                                <div class="clearfix"></div>

                                            </div>
                                        </li>
                                        <li>
                                            <a href="cart.html" class="e-btn pd-addcart">افزودن به سبد </a>
                                        </li>
                                        <li>
                                            {% if request.user.is_authenticated %}
{#                                                <form action="{% url 'Product:AddProductFaviorate' product.id %}" method="post" class="favorite-form">#}
{#                                                        {% csrf_token %}#}
{#                                                <button type="submit" class="e-btn light pd-heart">Add to Favorites</button>#}
{#<                                               </form>#}
                                            <a href="{% url 'Product:addfaviorate' product.id %}" class="e-btn light pd-heart add-to-favorites" data-product-id="{{ product.id }}">

                                                <svg
                                                xmlns="http://www.w3.org/2000/svg"
                                                xmlns:xlink="http://www.w3.org/1999/xlink"
                                                width="17px" height="16px">
                                                <path fill-rule="evenodd"  fill="rgb(90, 106, 137)"
                                                d="M15.616,1.939 C14.768,0.972 13.603,0.440 12.337,0.440 C11.387,0.440 10.516,0.755 9.751,1.377 C9.456,1.616 9.182,1.898 8.933,2.217 C8.683,1.898 8.409,1.616 8.115,1.377 C7.350,0.755 6.480,0.440 5.529,0.440 C4.262,0.440 3.098,0.972 2.249,1.939 C1.419,2.886 0.962,4.175 0.962,5.570 C0.962,7.002 1.465,8.308 2.547,9.681 C3.494,10.880 4.842,12.088 6.411,13.493 C6.940,13.967 7.540,14.504 8.163,15.077 C8.375,15.272 8.649,15.380 8.933,15.380 C9.218,15.380 9.491,15.272 9.703,15.077 C10.269,14.555 10.818,14.063 11.311,13.622 L11.458,13.490 C13.019,12.092 14.367,10.886 15.318,9.681 C16.400,8.309 16.904,7.003 16.904,5.570 C16.904,4.175 16.446,2.886 15.616,1.939 ZM5.529,1.905 C6.154,1.905 6.729,2.115 7.237,2.528 C7.702,2.906 8.028,3.387 8.219,3.724 C8.522,4.253 9.346,4.252 9.646,3.723 C9.838,3.387 10.163,2.906 10.628,2.528 C11.137,2.115 11.712,1.905 12.337,1.905 C13.198,1.905 13.989,2.266 14.566,2.923 C15.160,3.599 15.486,4.540 15.486,5.570 C15.486,6.662 15.095,7.644 14.220,8.754 C13.352,9.855 12.049,11.023 10.530,12.383 C10.045,12.817 9.501,13.304 8.932,13.823 C8.365,13.305 7.823,12.818 7.332,12.379 C5.821,11.025 4.515,9.857 3.647,8.754 C2.770,7.644 2.379,6.662 2.379,5.570 C2.379,4.540 2.706,3.599 3.300,2.923 C3.877,2.266 4.668,1.905 5.529,1.905 Z"/>
                                                </svg>
                                            </a>
                                            <div class="alert-message" id="fave-message"></div>
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Product/templates/wishlist.html
{% extends 'Shared/Base.html' %}
{% load static %}
{% block content %}
    <meta name="csrf-token" content="{{ csrf_token }}">
    <div class="e-shopcart-wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="e-shopcart-sec">
                    <div class="shopcart-table-wrap mb-30">
                        <form class="table-responsive">
                            <table class="shopcart-table">
                                <thead>
                                  <tr>
                                    <th>محصول </th>
                                    <th>قیمت </th>
                                    <th>وضعیت</th>
                                    <th>گزینه</th>
                                    <th>&nbsp;</th>
                                  </tr>
                                </thead>
                                <tbody>
                                {% for item in UserFaviorats %}
                                  <tr class="e-remove-wrap">
                                    <td >
                                        <div class="sc-productwrap">
                                            <a href="product_details.html" class="sc-product-thumb">
                                                {% if item.product.image %}
                                                <img src="{{ item.product.image.url}}" alt="محصول" class="img-fluid">
                                                {% endif %}
                                            </a>
                                            <div class="sc-product-details">
                                                <a href="product_details.html" class="sc-product-ttl">{{ item.product.name }}</a>
                                                <p class="sc-product-sz">{{ item.product.variations.size}} </p>
                                            </div>
                                        </div>
                                    </td>
                                    <td><span class="sc-product-prc">{{ item.product.base_price}}</span></td>
                                    <td><span class="sc-wishlist-status stock-availble">در انبار</span></td>
                                    <td>
                                        <a href="javascript:void(0);" class="e-btn wishlist-ac">افزودن به سبد </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'Product:deleteproductfaviorate' item.id %}" data-url="{% url 'Product:deleteproductfaviorate' item.id %}" data-item="{{ item.id }}"  class="sc-product-remove e-remove-product " >
                                            <img src="{% static 'assets/images/index1/svg/cut.svg' %}" alt="icon">
                                        </a>
                                    </td>
                                  </tr>
                                 {% endfor %}
                                </tbody>
                              </table>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}